kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: asa-back-route
  namespace: asa
spec:
  host: asa-back-asa.apps.cicd.arcus.soprasteria.com
  to:
    kind: Service
    name: asa-back-service
    weight: 1
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
status:
  ingress:
    - host: asa-back-asa.apps.cicd.arcus.soprasteria.com
      routerName: default
      conditions:
        - type: Admitted
          status: 'True'
          lastTransitionTime: '2023-10-04T11:54:14Z'
      wildcardPolicy: None
      routerCanonicalHostname: router-default.apps.cicd.arcus.soprasteria.com
