include:
  - local: common/cicd-functions/common.yml
  - local: common/cicd-functions/helm.yml
  - local: common/cicd-functions/kaniko.yml

image: node:18-alpine
before_script:
    - cd asa-ng

variables:
  ASA_PROJECT_DIR: "${CI_PROJECT_DIR}/asa-ng"
  APP_NAME: asa-ng

stages:
  - prepare
  - build
  - analyse
  - test
  - release
  - deploy


get-version:
  extends: .get-version
  script:
    - |
      if [ ${CI_COMMIT_TAG} ]; then
        VERSION=${CI_COMMIT_TAG}
      else
        VERSION="$(node -p require\(\'package.json\'\).version)-${CI_COMMIT_SHORT_SHA}"
      fi
    - echo "VERSION=${VERSION}" >> prepare.env

install-packages:
  stage: prepare
  script:
    - npm ci
  artifacts:
    paths:
      - asa-ng/node_modules/*

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - asa-ng/dist/*
  rules:
    - when: on_success

npm-audit:
  stage: analyse
  needs: [install-packages]
  script:
    - npm audit
  allow_failure: true
  rules:
    - when: on_success


test:
  stage: test
  needs: [install-packages]
  script:
    - npm run test
  rules:
    - when: on_success


build-and-publish-docker-image:
  extends: .kaniko-build-and-publish
  variables:
    DOCKERFILE_PATH: ${CONTEXT_DIR}/Dockerfile

publish-helm-chart:
  extends: .publish-helm-chart
  needs: [get-version, build-and-publish-docker-image]


deploy:
  extends: .deploy-helm-chart
  