include:
  project: "dep/library/ci-library"
  file: "stages/build-jobs/build-image.yml"

stages:
  - prepare
  - build
  - test
  - build_image

default:
  image: node:18-alpine

before_script:
  - cd asa-ng

install_packages:
  stage: prepare
  script:
    - npm ci
  artifacts:
    paths:
      - asa-ng/node_modules/*

build:
  stage: build
  needs: [install_packages]
  script:
    - npm run build
  artifacts:
    paths:
      - asa-ng/dist/*

test:
  stage: test
  needs: [install_packages]
  script:
    - npm run test