image: node:18-alpine
before_script:
    - cd asa-ng

stages:
  - prepare
  - build
  - analyse
  - test

install_packages:
  stage: prepare
  script:
    - npm ci
  artifacts:
    paths:
      - asa-ng/node_modules/*

build:
  stage: build
  needs: [install_packages]
  script:
    - npm run build
  artifacts:
    paths:
      - asa-ng/dist/*
  
sonarqube-check:
  stage: analyse
  needs: [install_packages]
  image: 
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: 
    - sonar-scanner
  allow_failure: true

test:
  stage: test
  needs: [install_packages]
  script:
    - npm run test