stages:
  - prepare
  - build
  - test

default:
  image: node:18-alpine

install_packages:
  stage: prepare
  before_script:
    - cd asa-ng
  script:
    - npm ci

build:
  stage: build
  needs: [install_packages]
  before_script:
    - cd asa-ng
  script:
    - npm run build

test:
  stage: test
  needs: [install_packages]
  before_script:
    - cd asa-ng
  script:
    - npm run test