include:
  - project: "dep/library/ci-library"
    ref: production
    file:
      - "stages/build-jobs/build-image.yml"
      - "main.deployment.yml"

image: node:18-alpine
before_script:
    - cd asa-ng

stages:
  - init
  - prepare
  - build
  - build-application
  - lint
  - analysis
  - security-check
  - test
  - build-image
  - deploy
  - destroy
  - pre-acceptance
  - acceptance

install_packages:
  stage: prepare
  script:
    - npm ci
  artifacts:
    paths:
      - asa-ng/node_modules/*

build:
  stage: build
  needs: [install_packages]
  script:
    - npm run build
  artifacts:
    paths:
      - asa-ng/dist/*

test:
  stage: test
  needs: [install_packages]
  script:
    - npm run test