include:
  - project: "dep/library/ci-library"
    ref: production
    file:
      - "stages/build-jobs/build-image.yml"
      - "stages/init-jobs/branch-lint.yml"
      - "main.deployment.yml"

stages:
  - prepare
  - build
  - test
  - build-image

before_script:
  - cd asa-ng

install_packages:
  stage: prepare
  image: node:18-alpine
  script:
    - npm ci
  artifacts:
    paths:
      - asa-ng/node_modules/*

build:
  stage: build
  needs: [install_packages]
  image: node:18-alpine
  script:
    - npm run build
  artifacts:
    paths:
      - asa-ng/dist/*

test:
  stage: test
  needs: [install_packages]
  image: node:18-alpine
  script:
    - npm run test