stages:
  - prepare
  - build
  - test
  - release

default:
  image: node:18-alpine

install_packages:
  stage: prepare
  before_script:
    - cd asa-ng
  script:
    - npm ci
  artifacts:
        paths:
          - asa-ng/node_modules/*

build:
  stage: build
  needs: [install_packages]
  before_script:
    - cd asa-ng
  script:
    - npm run build

test:
  stage: test
  needs: [install_packages]
  before_script:
    - cd asa-ng
  script:
    - npm run test

build_image:
  stage: release
  image: docker:24.0.3
  before_script:
    - cd asa-ng
  script:
    - docker build . -t asa-ng:0.0.1-SNAPSHOT
