include:
  - local: cicd-functions/kaniko.yml

image: node:18-alpine
before_script:
    - cd asa-ng

variables:
  ASA_PROJECT_DIR: "${CI_PROJECT_DIR}/asa-ng"

stages:
  - prepare
  - build
  - analyse
  - test
  - release
#  - deploy

get-version:
  stage: prepare
  variables:
    VERSION: latest
  script:
    - |
      if [ ${CI_COMMIT_TAG} ]; then
        VERSION=${CI_COMMIT_TAG}
      else
        VERSION="$(node -p require\(\'${ASA_PROJECT_DIR}/package.json\'\).version)-${CI_COMMIT_SHORT_SHA}"
      fi
    - echo "VERSION=${VERSION}" >> prepare.env
  artifacts:
    reports:
      dotenv: ${ASA_PROJECT_DIR}/prepare.env
  rules:
    - if: '$CI_COMMIT_BRANCH != "develop" && $CI_COMMIT_BRANCH != "master"'
      when: always


install-packages:
  stage: prepare
  script:
    - npm ci
  artifacts:
    paths:
      - asa-ng/node_modules/*

build:
  stage: build
  needs: [install-packages]
  script:
    - npm run build
  artifacts:
    paths:
      - asa-ng/dist/*
  
sonarqube-check:
  stage: analyse
  needs: [install-packages]
  image: 
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${ASA_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: 
    - sonar-scanner
  allow_failure: true

test:
  stage: test
  needs: [install-packages]
  script:
    - npm run test

build-and-publish-docker-image:
  stage: release
  needs: [get-version, build, test]
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: ['']
  variables:
    CONTEXT_DIR: "${ASA_PROJECT_DIR}"
    IMAGE_NAME: "${NEXUS_DOCKER_REPOSITORY_URL}/asa-ng"
    IMAGE_VERSION: ${VERSION}
  before_script:
    # Adds authentication to docker repository into kaniko config
    - echo "{\"auths\":{\"${NEXUS_DOCKER_REPOSITORY_URL}:${NEXUS_HTTPS_PORT}\":{\"username\":\"${DOCKER_CICD_USER}\",\"password\":\"${DOCKER_CICD_PASSWORD}\"}}}" > /kaniko/.docker/config.json
  script:
    - !reference [.kaniko-build-and-publish, script]
  rules:
    - if: '$CI_COMMIT_BRANCH != "develop" && $CI_COMMIT_BRANCH != "master"'
      when: always
# TODO : Thinking about rename steps and needs
publish-helm-chart:
  stage: release
  needs: [build-and-publish-docker-image]
  image:
    name: alpine/helm:3.13.3
  variables:
    WORKDIR: "${ASA_PROJECT_DIR}"
  before_script:
    - cd $WORKDIR
    - helm repo add asa-registry $NEXUS_HELM_REPOSITORY_URL --username $HELM_CICD_USER --password $HELM_CICD_PASSWORD
  script:
    - helm package ${WORKDIR}/helm
    - curl -u ${HELM_CICD_USER}:${HELM_CICD_PASSWORD} $NEXUS_HELM_REPOSITORY_URL --upload-file ${WORKDIR}/asa-ng-0.0.1.tgz -v
  rules:
    - if: '$CI_COMMIT_BRANCH != "develop" && $CI_COMMIT_BRANCH != "master"'
      when: always

# deploy:
#   stage: deploy
#   needs: [publish-helm-chart]
#   image:
#     name: alpine/helm:3.13.3
#   script:
#     - helm install asa-ng $NEXUS_HELM_REPOSITORY_URL/asa-ng
#   when:
#     never
  