stages:
  - prepare
  - build
  - test

default:
  image: node:18-alpine

setup:
  before_script:
    - cd asa-ng

install_packages:
  stage: prepare
  extends: setup
  script:
    - npm ci


build:
  stage: build
  extends: setup
  needs: [install_packages]
  script:
    - npm run build

test:
  stage: test
  extends: setup
  needs: [install_packages] 
  script:
    - npm run test