# First image to install quarkus-cli
FROM homebrew/ubuntu20.04:4.2.9 AS installer

RUN brew install quarkusio/tap/quarkus


# Second image : final image
FROM eclipse-temurin:21.0.2_13-jdk

RUN adduser --no-create-home --disabled-password --disabled-login hfauchery

COPY --from=installer /home/linuxbrew/.linuxbrew/Cellar /foreign-bins

ENV PATH="$PATH:/foreign-bins/quarkus/3.7.3/bin"
USER hfauchery

ENTRYPOINT ["tail", "-f", "/dev/null"]